#!/bin/sh
# chkconfig: - 80 12
# description:  The memcached daemon is a network memory cache service.
# processname: memcached
BIN=/usr/bin/memcachedb
USER=nobody
CON=2048

. /etc/init.d/functions

case "$1" in
	start)
		echo "Starting memcachedb"
		$BIN -d -m 16 -p 11211 -c $CON -u $USER -f /var/lib/memcachedb/default1.db -H /var/lib/memcachedb/ -P /var/run/memcachedb/pid
		echo 
	;;
	stop)	
		echo "Stoping memcachedb"
		kill -9 `cat /var/run/memcachedb/pid`
	;;
	restart)
                $0 stop
                $0 start
        ;;
	status)
                status -p /var/run/memcachedb/pid memcachedb
        ;;
esac
